<?php
// This is a automatically generated file by make_portfolio.py
$fsg_portfolio = array(
  'portfolio/dystopia' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,3748,False,2656,2868,False,2822,False,False,False,2717,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/the-dark-room' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => '6579,7364,False,False,False,False,6630,False,False,False,6735,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/peculiar-events' => array(
    'tile' => 90,
    'cols' => '3',
    'border' => 3,
    'include' => '7920,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/masculinity' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,False,False,False,False,5262,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/imperfect' => array(
    'tile' => 90,
    'cols' => '4',
    'border' => 3,
    'include' => '5156,4307,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/life-of-helmut' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,3745,3643,False,False,3646,False,False,False,False,False,3652,False,362,False,False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/how-i-move' => array(
    'tile' => 90,
    'cols' => '3,4',
    'border' => 3,
    'include' => 'False,8375,8372,8359,8365,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/the-schoolhouse' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/slaughterhouse-42' => array(
    'tile' => 90,
    'cols' => '3,2',
    'border' => 3,
    'include' => 'False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/how-i-met-death-and-became-friends-with-him' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,4173,False,False,3997,4846,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/story-of-a-vampire' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,False,False,False,False,False,False,4753',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/broken-doll' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,4203,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/nocturnal-awakenings' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,5079,5081,5082,5083,5084,5080',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/birds-and-branches' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,3670,2736,False,2734,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/finland-in-infrared' => array(
    'tile' => 90,
    'cols' => '3,2',
    'border' => 3,
    'include' => 'False,False,False,False,False,False,False,False,5598,5599,False,False,False,5378,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/conceptual' => array(
    'tile' => 90,
    'cols' => '3',
    'border' => 3,
    'include' => 'False,False,4642,False,False,False,False,False,4493,False,False,False,False,False,False,False,False,False,1862',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/humour' => array(
    'tile' => 90,
    'cols' => '3,2,3',
    'border' => 3,
    'include' => 'False,False,False,False,False,False,False,False,False,False,3426,False,False,False,False,False,False,False,1366',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/men' => array(
    'tile' => 90,
    'cols' => '3',
    'border' => 3,
    'include' => '2290,8019,False,4461,False,8020,False,False,False,7934,4470,4871,False,4368,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/women' => array(
    'tile' => 90,
    'cols' => '3',
    'border' => 3,
    'include' => 'False,False,False,False,7569,False,5895,False,False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/vehicles' => array(
    'tile' => 90,
    'cols' => '3',
    'border' => 3,
    'include' => 'False,False,False,False,False,False,False,False,False,False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio/still-life' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => '7210,False,False,3436,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-pics">',
    'spacer' => '',
    'footer' => '</div></div>',
    'extlinks' => 'false',
    'fixed' => 'height',
  ),
  'portfolio' => array(
    'tile' => 90,
    'cols' => '2',
    'border' => 3,
    'include' => 'False,6579,7920,False,5156,False,False,False,False,False,False,False,False,False,False;False,False,False,False,False,False',
    'header' => '<div class="portfolio-div"><div class="portfolio-left-pane">Series</div><div class="portfolio-pics">',
    'spacer' => '</div><div class="portfolio-separator"></div><div class="portfolio-pics">',
    'footer' => '</div><div class="portfolio-right-pane">Images</div></div>',
    'extlinks' => 'true',
    'fixed' => 'width',
  ),
);
?>
